### PR TITLE
Added presets and fix for issue #8

### PR DESCRIPTION
**Pull request by slightfoot**
Added presets support for `gcp` and `rackspace`.
Added presets/cidr test case.
Made Caddyfile syntax more flexible solving issue #8
Updated docs.

### CODE REVIEW

**Comment by captncraig** [comment]
Wow, this is really quite well done. Thank you!

**Comment by slightfoot** [comment]
Your welcome.

**Comment by jleclanche** [comment]
This is awesome. Does caddyserver.com pull from master?

**Comment by captncraig** [comment]
No, but I triggered a rebuild, so it should be there.

**Comment by slightfoot** [comment]
@captncraig It might be worth updating the docs on the Caddy site with the new presets?

https://caddyserver.com/docs/http.realip

**Pull request merged**
